var pList = {
    a:["Aa", "Aa", "Aa", "Aa",],
    b:["Bb", "Bb", "Bb", "Bb","Bb"],
    c:["Cc", "Cc", "Cc", "Cc", "Cc",],
    d:["Dd", "Dd", "Dd", "Dd", "Dd",],
    e:["Ee", "Ee", "Ee", "Ee", "Ee",],
    f:["Ff", "Ff", "Ff", "Ff", "Ff",],
    g:["Gg", "Gg", "Gg", "Gg", "Gg",],
    h:["Hh", "Hh", "Hh", "Hh", "Hh",],
    i:["Ii", "Ii", "Ii", "Ii",],
    j:["Jj", "Jj", "Jj", "Jj",],
    k:["Kk", "Kk", "Kk", "Kk",],
    l:["Ll", "Ll", "Ll", "Ll",],
    m:["Mm", "Mm", "Mm", "Mm",],
    n:["Nn", "Nn", "Nn", "Nn","Nn"],
    o:["Oo", "Oo", "Oo", "Oo","Oo"],
    p:["Pp", "Pp", "Pp", "Pp", "Pp",],
    q:["Qq", "Qq", "Qq", "Qq", "Qq",],
    r:["Rr", "Rr", "Rr", "Rr","Rr"],
    s:["Ss", "Ss", "Ss", "Ss", "Ss",],
    t:["Tt", "Tt", "Tt", "Tt",],
    u:["Uu", "Uu", "Uu","Uu"],
    v:["Vv", "Vv", "Vv", "Vv",],
    w:["Ww", "Ww", "Ww", "Ww",],
    x:["Xx", "Xx", "Xx", "Xx",],
    y:["Yy", "Yy", "Yy", "Yy",],
    z:["Zz", "Zz", "Zz", "Zz",],
}


var audioList = {
    a:["a1.mp3", "a2.mp3", "a3.mp3", "a4.mp3"],
    b:["b1.mp3", "b2.mp3", "b3.mp3", "b4.mp3","b5.mp3"],
    c:["c1.mp3", "c2.mp3", "c3.mp3", "c4.mp3","c5.mp3"],
    d:["d1.mp3", "d2.mp3", "d3.mp3", "d4.mp3", "d5.mp3"],
    e:["e1.mp3", "e2.mp3", "e3.mp3", "e4.mp3", "e5.mp3",],
    f:["f1.mp3", "f2.mp3", "f3.mp3", "f4.mp3", "f5.mp3",],
    g:["g1.mp3", "g2.mp3", "g3.mp3", "g4.mp3", "g5.mp3",],
    h:["h1.mp3", "h2.mp3", "h3.mp3", "h4.mp3", "h5.mp3",],
    i:["i1.mp3", "i2.mp3", "i3.mp3", "i4.mp3"],
    j:["j1.mp3", "j2.mp3", "j3.mp3", "j4.mp3",],
    k:["k1.mp3", "k2.mp3", "k3.mp3", "k4.mp3",],
    l:["l1.mp3", "l2.mp3", "l3.mp3", "l4.mp3",],
    m:["m1.mp3", "m2.mp3", "m3.mp3", "m4.mp3",],
    n:["n1.mp3", "n2.mp3", "n3.mp3", "n4.mp3","n5.mp3",],
    o:["o1.mp3", "o2.mp3", "o3.mp3", "o4.mp3","o5.mp3"],
    p:["p1.mp3", "p2.mp3", "p3.mp3", "p4.mp3", "p5.mp3",],
    q:["q1.mp3", "q2.mp3", "q3.mp3", "q4.mp3", "q5.mp3",],
    r:["r1.mp3", "r2.mp3", "r3.mp3", "r4.mp3","r5.mp3"],
    s:["s1.mp3", "s2.mp3", "s3.mp3", "s4.mp3", "s5.mp3",],
    t:["t1.mp3", "t2.mp3", "t3.mp3", "t4.mp3",],
    u:["u1.mp3", "u2.mp3", "u3.mp3","u4.mp3"],
    v:["v1.mp3", "v2.mp3", "v3.mp3", "v4.mp3",],
    w:["w1.mp3", "w2.mp3", "w3.mp3", "w4.mp3",],
    x:["x1.mp3", "x2.mp3", "x3.mp3", "x4.mp3",],
    y:["y1.mp3", "y2.mp3", "y3.mp3", "y4.mp3",],
    z:["z1.mp3", "z2.mp3", "z3.mp3", "z4.mp3",],
}
